requires 'CGI';
requires 'CGI::PSGI';
requires 'Plack::Util';
requires 'Plack::Request';
requires 'Moose';
requires 'Data::Dumper';
requires 'Path::Router';
requires 'Plack::App::Path::Router::PSGI';
